# Generated by Django 5.0.14 on 2026-06-12 10:52

# pyrefly: ignore [missing-import]
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(help_text='URL friendly name (e.g., urban-ladder-sofa)', max_length=255, unique=True)),
                ('brand', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('subcategory', models.CharField(max_length=100)),
                ('item_type', models.CharField(max_length=100)),
                ('finish', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/images/')),
                ('is_primary', models.BooleanField(default=False, help_text='Is this the main thumbnail?')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant_id', models.CharField(max_length=100, unique=True)),
                ('price', models.DecimalField(decimal_places=2, help_text='Selling price', max_digits=10)),
                ('compare_price', models.DecimalField(decimal_places=2, help_text='Original MRP', max_digits=10)),
                ('inventory_quantity', models.IntegerField(default=0, help_text='Total stock available')),
                ('inventory_reserved', models.IntegerField(default=0, help_text="Stock currently in someone's cart")),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='api.product')),
            ],
        ),
    ]
