# Generated by Django 5.0.14 on 2026-06-16 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Main headline for the banner (e.g., 'Summer Sale')", max_length=200)),
                ('subtitle', models.TextField(blank=True, help_text='Sub-text under the headline', null=True)),
                ('tag', models.CharField(blank=True, default='Featured', help_text="Small tag like 'New Arrival'", max_length=50, null=True)),
                ('image_url', models.URLField(help_text='Paste the URL of the hosted image', max_length=1000)),
                ('link_url', models.CharField(default='/products', help_text='Where should this banner take the user? (e.g., /products?category=Living Room)', max_length=500)),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to hide this banner from the website')),
                ('display_order', models.IntegerField(default=0, help_text='Lower numbers appear first (e.g., 1 comes before 5)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Hero Banner',
                'verbose_name_plural': 'Hero Banners',
                'ordering': ['display_order', '-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='compare_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Original MRP', max_digits=10, null=True),
        ),
    ]
