# Generated by Django 5.0.14 on 2026-06-16 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_banner_alter_productvariant_compare_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='image_url',
        ),
        migrations.AddField(
            model_name='banner',
            name='image',
            field=models.ImageField(default=2, help_text='Upload the banner image from your computer', upload_to='banners/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='banner',
            name='link_url',
            field=models.CharField(default='/products', help_text='Where should this banner take the user?', max_length=500),
        ),
    ]
