# Generated by Django 6.0.6 on 2026-07-16 08:56

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_subcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('customer_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('business_type', models.CharField(choices=[('Hotel', 'Hotel'), ('Hostel', 'Hostel'), ('Office', 'Office'), ('Enterprise', 'Enterprise'), ('Hospital', 'Hospital'), ('School', 'School'), ('College', 'College'), ('Apartment', 'Apartment'), ('Builder', 'Builder'), ('Corporate', 'Corporate'), ('Other', 'Other')], max_length=50)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('pincode', models.CharField(blank=True, max_length=20, null=True)),
                ('categories', models.JSONField(default=list)),
                ('estimated_quantity', models.CharField(blank=True, max_length=100, null=True)),
                ('estimated_budget', models.CharField(blank=True, max_length=100, null=True)),
                ('delivery_date', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='bulk_orders/attachments/', validators=[api.models.validate_file_size])),
                ('status', models.CharField(choices=[('New', 'New'), ('Contacted', 'Contacted'), ('Quotation Sent', 'Quotation Sent'), ('Negotiation', 'Negotiation'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Completed', 'Completed')], default='New', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BusinessBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('small_heading', models.CharField(default='Hostels • Enterprise • Hotels • Office', max_length=100)),
                ('title', models.CharField(default='Videms for Business', max_length=200)),
                ('subtitle', models.CharField(default='Special Pricing & Custom Solutions', max_length=255)),
                ('button_text', models.CharField(default='Place Bulk Order', max_length=50)),
                ('button_color', models.CharField(default='#f97316', max_length=20)),
                ('gradient_overlay', models.CharField(default='linear-gradient(to right, rgba(0,0,0,0.8), rgba(0,0,0,0.4))', max_length=100)),
                ('image', models.ImageField(help_text='Background image for the banner', upload_to='business_banners/')),
                ('display_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Business Banners',
                'ordering': ['display_order', '-created_at'],
            },
        ),
    ]
