# Generated by Django 6.0.6 on 2026-07-18 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_bulkorder_businessbanner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Uncheck to hide this banner from the website'),
        ),
        migrations.AlterField(
            model_name='businessbanner',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='status',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='combination',
            name='status',
            field=models.BooleanField(db_index=True, default=True, help_text='Enable/Disable combination'),
        ),
        migrations.AlterField(
            model_name='homepagebestseller',
            name='status',
            field=models.BooleanField(db_index=True, default=True, help_text='Enable/Disable on homepage'),
        ),
        migrations.AlterField(
            model_name='homepagenewarrival',
            name='status',
            field=models.BooleanField(db_index=True, default=True, help_text='Enable/Disable on homepage'),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='item_type',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='subcategory',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='status',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
